# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Administrator\Desktop\account managed\forms\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(993, 557))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.em_progressBar = QtWidgets.QProgressBar(self.tab)
        self.em_progressBar.setProperty("value", 0)
        self.em_progressBar.setObjectName("em_progressBar")
        self.gridLayout_2.addWidget(self.em_progressBar, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.em_log_msg = QtWidgets.QTextBrowser(self.tab)
        self.em_log_msg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.em_log_msg.setObjectName("em_log_msg")
        self.gridLayout_2.addWidget(self.em_log_msg, 2, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.em_user = QtWidgets.QLineEdit(self.tab)
        self.em_user.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.em_user.setObjectName("em_user")
        self.verticalLayout_3.addWidget(self.em_user)
        self.em_pwd = QtWidgets.QLineEdit(self.tab)
        self.em_pwd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.em_pwd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.em_pwd.setObjectName("em_pwd")
        self.verticalLayout_3.addWidget(self.em_pwd)
        self.em_login = QtWidgets.QPushButton(self.tab)
        self.em_login.setMaximumSize(QtCore.QSize(9999999, 16777215))
        self.em_login.setObjectName("em_login")
        self.verticalLayout_3.addWidget(self.em_login)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.em_function_zone = QtWidgets.QTabWidget(self.tab)
        self.em_function_zone.setMinimumSize(QtCore.QSize(811, 475))
        self.em_function_zone.setObjectName("em_function_zone")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.em_mass_recipients = QtWidgets.QLineEdit(self.tab_5)
        self.em_mass_recipients.setGeometry(QtCore.QRect(10, 10, 671, 31))
        self.em_mass_recipients.setInputMask("")
        self.em_mass_recipients.setText("")
        self.em_mass_recipients.setObjectName("em_mass_recipients")
        self.em_mass_content = QtWidgets.QTextEdit(self.tab_5)
        self.em_mass_content.setGeometry(QtCore.QRect(10, 90, 721, 191))
        self.em_mass_content.setMaximumSize(QtCore.QSize(721, 16777215))
        self.em_mass_content.setObjectName("em_mass_content")
        self.em_mass_subject = QtWidgets.QLineEdit(self.tab_5)
        self.em_mass_subject.setGeometry(QtCore.QRect(140, 50, 511, 31))
        self.em_mass_subject.setObjectName("em_mass_subject")
        self.em_mass_send = QtWidgets.QPushButton(self.tab_5)
        self.em_mass_send.setGeometry(QtCore.QRect(280, 360, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.em_mass_send.setFont(font)
        self.em_mass_send.setObjectName("em_mass_send")
        self.em_mass_add_attachment = QtWidgets.QPushButton(self.tab_5)
        self.em_mass_add_attachment.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.em_mass_add_attachment.setObjectName("em_mass_add_attachment")
        self.em_mass_import_file_content = QtWidgets.QPushButton(self.tab_5)
        self.em_mass_import_file_content.setGeometry(QtCore.QRect(730, 90, 61, 191))
        self.em_mass_import_file_content.setMaximumSize(QtCore.QSize(721, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.em_mass_import_file_content.setFont(font)
        self.em_mass_import_file_content.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em_mass_import_file_content.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.em_mass_import_file_content.setObjectName("em_mass_import_file_content")
        self.em_mass_import_file_recipients = QtWidgets.QPushButton(self.tab_5)
        self.em_mass_import_file_recipients.setGeometry(QtCore.QRect(690, 10, 111, 31))
        self.em_mass_import_file_recipients.setObjectName("em_mass_import_file_recipients")
        self.em_mass_text = QtWidgets.QRadioButton(self.tab_5)
        self.em_mass_text.setGeometry(QtCore.QRect(230, 330, 115, 19))
        self.em_mass_text.setChecked(True)
        self.em_mass_text.setObjectName("em_mass_text")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(310, 310, 72, 15))
        self.label_4.setObjectName("label_4")
        self.em_mass_html = QtWidgets.QRadioButton(self.tab_5)
        self.em_mass_html.setGeometry(QtCore.QRect(390, 330, 115, 19))
        self.em_mass_html.setObjectName("em_mass_html")
        self.em_mass_clock_send = QtWidgets.QPushButton(self.tab_5)
        self.em_mass_clock_send.setGeometry(QtCore.QRect(590, 320, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.em_mass_clock_send.setFont(font)
        self.em_mass_clock_send.setObjectName("em_mass_clock_send")
        self.em_mass_evday = QtWidgets.QCheckBox(self.tab_5)
        self.em_mass_evday.setEnabled(False)
        self.em_mass_evday.setGeometry(QtCore.QRect(640, 410, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.em_mass_evday.setFont(font)
        self.em_mass_evday.setCheckable(True)
        self.em_mass_evday.setObjectName("em_mass_evday")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(590, 380, 179, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.em_mass_clock = QtWidgets.QTimeEdit(self.layoutWidget)
        self.em_mass_clock.setObjectName("em_mass_clock")
        self.horizontalLayout.addWidget(self.em_mass_clock)
        self.em_mass_attachment = QtWidgets.QListWidget(self.tab_5)
        self.em_mass_attachment.setGeometry(QtCore.QRect(0, 300, 211, 171))
        self.em_mass_attachment.setObjectName("em_mass_attachment")
        self.em_mass_clock_send.raise_()
        self.em_mass_evday.raise_()
        self.layoutWidget.raise_()
        self.em_mass_recipients.raise_()
        self.em_mass_content.raise_()
        self.em_mass_subject.raise_()
        self.em_mass_send.raise_()
        self.em_mass_add_attachment.raise_()
        self.em_mass_import_file_content.raise_()
        self.em_mass_import_file_recipients.raise_()
        self.em_mass_text.raise_()
        self.label_4.raise_()
        self.em_mass_html.raise_()
        self.em_mass_attachment.raise_()
        self.em_function_zone.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.em_auto_start_reply = QtWidgets.QPushButton(self.tab_6)
        self.em_auto_start_reply.setGeometry(QtCore.QRect(260, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.em_auto_start_reply.setFont(font)
        self.em_auto_start_reply.setObjectName("em_auto_start_reply")
        self.em_auto_text = QtWidgets.QRadioButton(self.tab_6)
        self.em_auto_text.setGeometry(QtCore.QRect(240, 320, 115, 19))
        self.em_auto_text.setCheckable(True)
        self.em_auto_text.setChecked(True)
        self.em_auto_text.setObjectName("em_auto_text")
        self.em_auto_content = QtWidgets.QTextEdit(self.tab_6)
        self.em_auto_content.setGeometry(QtCore.QRect(10, 90, 721, 191))
        self.em_auto_content.setMaximumSize(QtCore.QSize(721, 16777215))
        self.em_auto_content.setObjectName("em_auto_content")
        self.em_auto_import_file_content = QtWidgets.QPushButton(self.tab_6)
        self.em_auto_import_file_content.setGeometry(QtCore.QRect(730, 90, 61, 191))
        self.em_auto_import_file_content.setMaximumSize(QtCore.QSize(721, 16777215))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.em_auto_import_file_content.setFont(font)
        self.em_auto_import_file_content.setFocusPolicy(QtCore.Qt.NoFocus)
        self.em_auto_import_file_content.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.em_auto_import_file_content.setObjectName("em_auto_import_file_content")
        self.em_auto_add_attachment = QtWidgets.QPushButton(self.tab_6)
        self.em_auto_add_attachment.setGeometry(QtCore.QRect(10, 280, 75, 23))
        self.em_auto_add_attachment.setObjectName("em_auto_add_attachment")
        self.em_auto_html = QtWidgets.QRadioButton(self.tab_6)
        self.em_auto_html.setGeometry(QtCore.QRect(400, 320, 115, 19))
        self.em_auto_html.setObjectName("em_auto_html")
        self.em_auto_subject = QtWidgets.QLineEdit(self.tab_6)
        self.em_auto_subject.setGeometry(QtCore.QRect(140, 50, 511, 31))
        self.em_auto_subject.setObjectName("em_auto_subject")
        self.label_2 = QtWidgets.QLabel(self.tab_6)
        self.label_2.setGeometry(QtCore.QRect(320, 300, 72, 15))
        self.label_2.setObjectName("label_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 791, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.em_auto_import_file_recipient = QtWidgets.QPushButton(self.layoutWidget1)
        self.em_auto_import_file_recipient.setObjectName("em_auto_import_file_recipient")
        self.horizontalLayout_2.addWidget(self.em_auto_import_file_recipient)
        self.em_auto_recipients = QtWidgets.QLineEdit(self.layoutWidget1)
        self.em_auto_recipients.setMinimumSize(QtCore.QSize(0, 31))
        self.em_auto_recipients.setObjectName("em_auto_recipients")
        self.horizontalLayout_2.addWidget(self.em_auto_recipients)
        self.em_auto_reply_all = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.em_auto_reply_all.setFont(font)
        self.em_auto_reply_all.setObjectName("em_auto_reply_all")
        self.horizontalLayout_2.addWidget(self.em_auto_reply_all)
        self.em_auto_attachment = QtWidgets.QListWidget(self.tab_6)
        self.em_auto_attachment.setGeometry(QtCore.QRect(0, 300, 211, 171))
        self.em_auto_attachment.setObjectName("em_auto_attachment")
        self.listView = QtWidgets.QListView(self.tab_6)
        self.listView.setGeometry(QtCore.QRect(1000, 160, 256, 192))
        self.listView.setObjectName("listView")
        self.em_function_zone.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.em_function_zone.addTab(self.tab_7, "")
        self.gridLayout_2.addWidget(self.em_function_zone, 0, 1, 3, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.menu.addSeparator()
        self.menu.addAction(self.actionFile)
        self.menu_5.addSeparator()
        self.menu_5.addSeparator()
        self.menu_5.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.em_function_zone.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "日志消息"))
        self.em_user.setPlaceholderText(_translate("MainWindow", "发送者邮箱账号"))
        self.em_pwd.setPlaceholderText(_translate("MainWindow", "发送者邮箱密码"))
        self.em_login.setText(_translate("MainWindow", "登录"))
        self.em_mass_recipients.setPlaceholderText(_translate("MainWindow", "接收者邮箱：多个请使用“,”相隔"))
        self.em_mass_content.setPlaceholderText(_translate("MainWindow", "请在这里输入正文"))
        self.em_mass_subject.setPlaceholderText(_translate("MainWindow", "请输入邮件主题"))
        self.em_mass_send.setText(_translate("MainWindow", "立即发送"))
        self.em_mass_add_attachment.setText(_translate("MainWindow", "添加附件"))
        self.em_mass_import_file_content.setText(_translate("MainWindow", "从\n"
"文\n"
"件\n"
"导\n"
"入\n"
"内\n"
"容"))
        self.em_mass_import_file_recipients.setText(_translate("MainWindow", "从文件导入"))
        self.em_mass_text.setText(_translate("MainWindow", "text"))
        self.label_4.setText(_translate("MainWindow", "文本类型"))
        self.em_mass_html.setText(_translate("MainWindow", "html"))
        self.em_mass_clock_send.setText(_translate("MainWindow", "开启定时发送"))
        self.em_mass_evday.setText(_translate("MainWindow", "每天发送"))
        self.label.setText(_translate("MainWindow", "定时时间"))
        self.em_function_zone.setTabText(self.em_function_zone.indexOf(self.tab_5), _translate("MainWindow", "邮件群发"))
        self.em_auto_start_reply.setText(_translate("MainWindow", "开启自动回复"))
        self.em_auto_text.setText(_translate("MainWindow", "text"))
        self.em_auto_content.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.em_auto_content.setPlaceholderText(_translate("MainWindow", "请在这里输入正文"))
        self.em_auto_import_file_content.setText(_translate("MainWindow", "从\n"
"文\n"
"件\n"
"导\n"
"入\n"
"内\n"
"容"))
        self.em_auto_add_attachment.setText(_translate("MainWindow", "添加附件"))
        self.em_auto_html.setText(_translate("MainWindow", "html"))
        self.em_auto_subject.setPlaceholderText(_translate("MainWindow", "请输入邮件主题"))
        self.label_2.setText(_translate("MainWindow", "文本类型"))
        self.em_auto_import_file_recipient.setText(_translate("MainWindow", "从文件导入"))
        self.em_auto_recipients.setPlaceholderText(_translate("MainWindow", "对特定人回复：多个请使用“,”相隔"))
        self.em_auto_reply_all.setText(_translate("MainWindow", "对所有人回复"))
        self.em_function_zone.setTabText(self.em_function_zone.indexOf(self.tab_6), _translate("MainWindow", "自动回复"))
        self.em_function_zone.setTabText(self.em_function_zone.indexOf(self.tab_7), _translate("MainWindow", "扩展功能"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "邮箱"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "qq"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "微信"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "短信"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "工具"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "帮助"))
        self.menu_5.setTitle(_translate("MainWindow", "编辑"))
        self.menu_6.setTitle(_translate("MainWindow", "代码"))
        self.actionFile.setText(_translate("MainWindow", "File"))

